import 'package:flutter/material.dart';
import 'package:freetanii/configs/colors_custom.dart';

class Partner {
  final String image, text, title, description;
  final int id;
  final Color color;
  final IconData icon;

  Partner(
      {required this.image,
      required this.title,
      required this.text,
      required this.description,
      required this.id,
      required this.color,
      required this.icon});
}

List<Partner> partners = [
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'WARUNG BU JOKO',
    text: 'Img 1',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_6.jpeg',
    title: 'WARUNG SETIA',
    text: 'Img 2',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_9.jpeg',
    title: 'TOKO CANTIK',
    text: 'Img 3',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'KIOS INDAH',
    text: 'Img 4',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_7.jpeg',
    title: 'WARUNG BU JOKO',
    text: 'Img 5',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_7.jpeg',
    title: 'WARUNG PAK HAJI',
    text: 'Img 6',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_8.jpeg',
    title: 'KEDAI HEMAT',
    text: 'Img 7',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_6.jpeg',
    title: 'WARUNG BERKAH',
    text: 'Img 8',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_9.jpeg',
    title: 'WARUNG JOSS',
    text: 'Img 9',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_7.jpeg',
    title: 'TOKO BUAH CIKA',
    text: 'Img 10',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'BEST FASHION',
    text: 'Img 11',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_6.jpeg',
    title: 'TOKO KADO BEST',
    text: 'Img 12',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_9.jpeg',
    title: 'WARUNG BU JOKO',
    text: 'Img 13',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'TOKO MERDEKA',
    text: 'Img 14',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_8.jpeg',
    title: 'TOKO MERPATI',
    text: 'Img 15',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'WARUNG BU NIA',
    text: 'Img 16',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/partner/img_5.jpeg',
    title: 'TOKO MEDSOS',
    text: 'Img 17',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_7.jpeg',
    title: 'KEDAI ALFA',
    text: 'Img 18',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_6.jpeg',
    title: 'TOKO CERIA',
    text: 'Img 19',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_9.jpeg',
    title: 'SMILE FASHION',
    text: 'Img 20',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
  Partner(
    image: 'assets/images/corousel/img_7.jpeg',
    title: 'TOKO ANUGRAH',
    text: 'Img 21',
    description: 'RT 01 RW 02',
    id: 1,
    color: Color(whiteCustom),
      icon: Icons.cloud_done_rounded),
];
